spring:
  application:
    name: mopl
  profiles:
    active: dev

server:
  port: 8080

tmdb:
  api:
    key: ${TMDB_API_KEY}

playlist:
  hard-delete:
    cron: "0 1 0 * * *"
    retention-months: 1
